- name: "Installing VIM"
  apt: pkg=vim state=installed

- name: "Installing GIT"
  apt: pkg=git state=installed

- name: "Installing build-essential"
  apt: pkg=build-essential state=installed

- name: "Installing devscripts"
  apt: pkg=devscripts state=installed

- name: "Installing SDL Libraries"
  apt: pkg={{item}} state=installed
  with_items:
    - libsdl2-2.0-0
    - libsdl2-dev
    - libsdl2-image-2.0-0
    - libsdl2-image-dev
    - libsdl2-ttf-2.0-0
    - libsdl2-ttf-dev
    - libsdl2-mixer-2.0-0
    - libsdl2-mixer-dev
